---
- hosts: raspi
  remote_user: ubuntu
  roles:
    - role: wireguard
      tags: [ wiregurad ]
    - role: traefik
      tags: [ traefik ] 

  pre_tasks:

    - name: set hostname to raspi
      hostname:
        name: raspi
      become: yes

    - name: packages to install
      package:
        name:
          - wireguard
          - docker.io
          - docker-compose
          - qrencode
        state: latest
      become: yes
