---
- hosts: raspi
  remote_user: ubuntu
  roles:
    - role: wireguard
      tags: [ wiregurad ]
    - role: traefik
      tags: [ traefik ] 
    - role: pihole
      tags: [ pihole ] 
    - role: homebridge
      tags: [ homebridge ]

  pre_tasks:

    - name: set hostname to raspi
      hostname:
        name: raspi
      become: yes

    - name: packages to install
      package:
        name:
          - zsh
          - tmux
          - mosh
          - docker.io
          - docker-compose
        state: latest
      become: yes
