---
- hosts: raspi
  remote_user: ubuntu

  tasks:

    - name: set hostname to raspi
      hostname:
        name: raspi
      become: yes
 
    - name: setup wireguard
      block:
        - name: wireguard installed
          package:
            name: wireguard
            state: present
          become: yes   

        - name: ipv6 forwarding enabled
          sysctl:
            name: net.ipv4.ip_forward
            value: '1'
            sysctl_set: yes
            state: present
            reload: yes
          become: yes

        - name: ipv6 forwarding enabled
          sysctl:
            name: net.ipv6.conf.all.forwarding
            value: '1'
            sysctl_set: yes
            state: present
            reload: yes
          become: yes

