version: '3'

services:
  traefik:
    image: traefik:latest
    restart: unless-stopped
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    networks:
      - web
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      #- ./traefik.yml:/etc/traefik/traefik.yml
      #- ./run/conf:/traefik/conf
      #- ./run/ssl:/traefik/ssl
      #- ./run/logs:/traefik/logs

    # ...
  whoami:
    # A container that exposes an API to show its IP address
    image: containous/whoami
    networks:
      - web
    labels:
      - "traefik.http.routers.whoami.rule=Path(`/whoami`)"
networks: 
  web: 
    external: 
      name: web